In [55]:
import numpy as np

In [56]:
np.__version__

'1.22.4'

In [57]:
import numpy as np
np.__version__

'1.22.4'

In [58]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [59]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [60]:
a = np.array([1,2,3,4,5,6,9])
a[2]

3

In [61]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [62]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [63]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [64]:
n = np.array([[0,1,2],[3,4,5],[6,7,8]])
n

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [65]:
n[:,1]

array([1, 4, 7])

In [66]:
n[:,]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [67]:
np.random.seed(2)
np.random.rand(5,2)
100 * np.random.randn(5,2)

array([[  55.14540445,  229.22080128],
       [   4.1539393 , -111.79254451],
       [  53.90583206,  -59.61596998],
       [  -1.91304965,  117.50012195],
       [ -74.78709493,    0.9025251 ]])

In [68]:
np.random.randint(low=0,high=440, size=(3,6))

array([[211, 121,  31,  80,  52, 238],
       [ 50, 132, 218, 319, 207,  49],
       [295, 430, 136, 434, 271, 233]])

In [69]:
a = np.arange(5)
b = (10 + (a * 2)) ** 2

In [70]:
b

array([100, 144, 196, 256, 324])

In [71]:
a + b

array([100, 145, 198, 259, 328])

In [72]:
a >=2 

array([False, False,  True,  True,  True])

In [73]:
a < b

array([ True,  True,  True,  True,  True])

In [74]:
a[a < 2]

array([0, 1])

In [75]:
a.sum()

10

In [76]:
a.mean()

2.0

In [77]:
n.min()

0

In [78]:
import pandas as pd

In [79]:
df = pd.read_csv('data.csv')

print(df.to_string()) 

                Make                                Model  Year                              Engine Fuel Type  Engine HP  Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors                                         Market Category Vehicle Size        Vehicle Style  highway MPG  city mpg  Popularity     MSRP
0                BMW                           1 Series M  2011                   premium unleaded (required)      335.0               6.0            MANUAL   rear wheel drive              2.0                   Factory Tuner,Luxury,High-Performance      Compact                Coupe           26        19        3916    46135
1                BMW                             1 Series  2011                   premium unleaded (required)      300.0               6.0            MANUAL   rear wheel drive              2.0                                      Luxury,Performance      Compact          Convertible           28        19        3916    40650
2                BM

In [80]:
len(df.index)

11914

In [81]:
df2 = df.groupby(['Make'])['Make'].count()
df2

Make
Acura             252
Alfa Romeo          5
Aston Martin       93
Audi              328
BMW               334
Bentley            74
Bugatti             3
Buick             196
Cadillac          397
Chevrolet        1123
Chrysler          187
Dodge             626
FIAT               62
Ferrari            69
Ford              881
GMC               515
Genesis             3
HUMMER             17
Honda             449
Hyundai           303
Infiniti          330
Kia               231
Lamborghini        52
Land Rover        143
Lexus             202
Lincoln           164
Lotus              29
Maserati           58
Maybach            16
Mazda             423
McLaren             5
Mercedes-Benz     353
Mitsubishi        213
Nissan            558
Oldsmobile        150
Plymouth           82
Pontiac           186
Porsche           136
Rolls-Royce        31
Saab              111
Scion              60
Spyker              3
Subaru            256
Suzuki            351
Tesla              18
Toyot

In [82]:
df.loc[df['Make'] == 'Audi'].groupby(['Model'])['Model'].count()

Model
100                15
200                 6
80                  6
90                  9
A3                 47
A4                 25
A4 allroad          3
A5                  9
A6                 23
A7                 10
A8                  6
Cabriolet           3
Coupe               2
Q3                 14
Q5                 20
Q7                 15
R8                 25
RS 4                3
RS 5                6
RS 6                1
RS 7                3
S3                  6
S4                 12
S5                  9
S6                  5
S7                  4
S8                  4
SQ5                 6
TT                  6
TT RS               2
TTS                 4
V8                  3
allroad             8
allroad quattro     8
Name: Model, dtype: int64

In [83]:
df.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [86]:
df['Engine Cylinders']. median()

6.0

In [93]:
df['Engine Cylinders'] == 'null'

0        False
1        False
2        False
3        False
4        False
         ...  
11909    False
11910    False
11911    False
11912    False
11913    False
Name: Engine Cylinders, Length: 11914, dtype: bool

In [95]:
df["Engine Cylinders"] = df["Engine Cylinders"].fillna(6.0)
df.isnull().sum()
df['Engine Cylinders']. median()

6.0

In [100]:
vary = df.loc[df['Make'] == 'Lotus']
vary
vary[['Engine HP', 'Engine Cylinders']].drop_duplicates()

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0